name: CI

on:
  schedule:
    - cron:  '0 1 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        redis-version: ['5', '6', 'latest']

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      env:
        PY_VERSION: ${{ matrix.python-version }}
        REDIS_VERSION: ${{ matrix.redis-version }}
      run: |
        docker-compose run --rm test
